In [1]:
import pandas as pd
import seaborn as sns
import acquire

## Acquire and Summarize

1. Acquire data from the cloud database.

    You will want to end with a single dataframe. Include the logerror field and all other fields related to the properties that are available. You will end up using all the tables in the database.

    <b><i>Be sure to do the correct join (inner, outer, etc.). We do not want to eliminate properties purely because they may have a null value for airconditioningtypeid.</i></b> - Only include properties with a transaction in 2017, and include only the last transaction for each property (so no duplicate property ID's), along with zestimate error and date of transaction. (Hint: read the docs for the .duplicated method) - Only include properties that have a latitude and longitude value.
    
    
2. Summarize your data (summary stats, info, dtypes, shape, distributions, value_counts, etc.)


3. Write a function that takes in a dataframe of observations and attributes and returns a dataframe where each row is an atttribute name, the first column is the number of rows with missing values for that attribute, and the second column is percent of total rows that have missing values for that attribute. Run the function and document takeaways from this on how you want to handle missing values.

In [2]:
df = acquire.zillow_data()
df

,parcelid,typeconstructiontypeid,storytypeid,propertylandusetypeid,heatingorsystemtypeid,buildingclasstypeid,architecturalstyletypeid,airconditioningtypeid,id,basementsqft,...,id,logerror,transactiondate,airconditioningdesc,architecturalstyledesc,buildingclassdesc,heatingorsystemdesc,propertylandusedesc,storydesc,typeconstructiondesc
0,14297519,NaN,NaN,261.0,NaN,None,NaN,NaN,1727539,NaN,...,0,0.025595,2017-01-01,None,None,None,None,Single Family Residential,None,None
1,17052889,NaN,NaN,261.0,NaN,None,NaN,NaN,1387261,NaN,...,1,0.055619,2017-01-01,None,None,None,None,Single Family Residential,None,None
2,14186244,NaN,NaN,261.0,NaN,None,NaN,NaN,11677,NaN,...,2,0.005383,2017-01-01,None,None,None,None,Single Family Residential,None,None
3,12177905,NaN,NaN,261.0,2.0,None,NaN,NaN,2288172,NaN,...,3,-0.103410,2017-01-01,None,None,None,Central,Single Family Residential,None,None
4,12095076,NaN,NaN,261.0,2.0,None,NaN,1.0,781532,NaN,...,6,-0.001011,2017-01-01,Central,None,None,Central,Single Family Residential,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52436,12412492,NaN,NaN,261.0,2.0,None,NaN,NaN,2274245,NaN,...,77607,0.001082,2017-09-19,None,None,None,Central,Single Family Residential,None,None
52437,11000655,NaN,NaN,261.0,2.0,None,NaN,NaN,673515,NaN,...,77609,0.020615,2017-09-20,None,None,None,Central,Single Family Residential,None,None
52438,17239384,NaN,NaN,261.0,NaN,None,NaN,NaN,2968375,NaN,...,77610,0.013209,2017-09-21,None,None,None,None,Single Family Residential,None,None
52439,12773139,NaN,NaN,261.0,2.0,None,NaN,1.0,1843709,NaN,...,77611,0.037129,2017-09-21,Central,None,None,Central,Single Family Residential,None,None
52440,12826780,NaN,NaN,261.0,2.0,None,NaN,NaN,1187175,NaN,...,77612,0.007204,2017-09-25,None,None,None,Central,Single Family Residential,None,None

In [3]:
df.shape

(52441, 69)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52441 entries, 0 to 52440
Data columns (total 69 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   parcelid                      52441 non-null  int64
 1   typeconstructiontypeid        76 non-null     float64
 2   storytypeid                   47 non-null     float64
 3   propertylandusetypeid         52441 non-null  float64
 4   heatingorsystemtypeid         33935 non-null  float64
 5   buildingclasstypeid           0 non-null      object
 6   architecturalstyletypeid      70 non-null     float64
 7   airconditioningtypeid         13638 non-null  float64
 8   id                            52441 non-null  int64
 9   basementsqft                  47 non-null     float64
 10  bathroomcnt                   52441 non-null  float64
 11  bedroomcnt                    52441 non-null  float64
 12  buildingqualitytypeid         33740 non-null  float64
 13  calculatedbathnbr             52304 non-null  float64
 14  decktypeid                    389 non-null    float64
 15  finishedfloor1squarefeet      4381 non-null   float64
 16  calculatedfinishedsquarefeet  52359 non-null  float64
 17  finishedsquarefeet12          52194 non-null  float64
 18  finishedsquarefeet13          0 non-null      object
 19  finishedsquarefeet15          0 non-null      object
 20  finishedsquarefeet50          4381 non-null   float64
 21  finishedsquarefeet6           165 non-null    float64
 22  fips                          52441 non-null  float64
 23  fireplacecnt                  7243 non-null   float64
 24  fullbathcnt                   52304 non-null  float64
 25  garagecarcnt                  18015 non-null  float64
 26  garagetotalsqft               18015 non-null  float64
 27  hashottuborspa                1515 non-null   float64
 28  latitude                      52441 non-null  float64
 29  longitude                     52441 non-null  float64
 30  lotsizesquarefeet             52072 non-null  float64
 31  poolcnt                       11096 non-null  float64
 32  poolsizesum                   867 non-null    float64
 33  pooltypeid10                  444 non-null    float64
 34  pooltypeid2                   1071 non-null   float64
 35  pooltypeid7                   10009 non-null  float64
 36  propertycountylandusecode     52441 non-null  object
 37  propertyzoningdesc            33848 non-null  object
 38  rawcensustractandblock        52441 non-null  float64
 39  regionidcity                  51404 non-null  float64
 40  regionidcounty                52441 non-null  float64
 41  regionidneighborhood          19033 non-null  float64
 42  regionidzip                   52415 non-null  float64
 43  roomcnt                       52441 non-null  float64
 44  threequarterbathnbr           6724 non-null   float64
 45  unitcnt                       33847 non-null  float64
 46  yardbuildingsqft17            1937 non-null   float64
 47  yardbuildingsqft26            63 non-null     float64
 48  yearbuilt                     52325 non-null  float64
 49  numberofstories               14561 non-null  float64
 50  fireplaceflag                 81 non-null     float64
 51  structuretaxvaluedollarcnt    52357 non-null  float64
 52  taxvaluedollarcnt             52440 non-null  float64
 53  assessmentyear                52441 non-null  float64
 54  landtaxvaluedollarcnt         52440 non-null  float64
 55  taxamount                     52437 non-null  float64
 56  taxdelinquencyflag            2079 non-null   object
 57  taxdelinquencyyear            2079 non-null   float64
 58  censustractandblock           52318 non-null  float64
 59  id                            52441 non-null  int64
 60  logerror                      52441 non-null  float64
 61  transactiondate               52441 non-null  object
 62  airconditioningdesc           13638 non-null  object
 63  architecturalstyledesc        70 non-null     object
 64  buildingclassdesc             0 non-null      object
 65  heatingorsystemdesc           33935 non-null  object
 66  propertylandusedesc           52441 non-null  object
 67  storydesc                     47 non-null     object
 68  typeconstructiondesc          76 non-null     object
dtypes: float64(52), int64(3), object(14)
memory usage: 27.6+ MB

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
parcelid,52441.0,1.299912e+07,3.411444e+06,1.071186e+07,1.151022e+07,1.257764e+07,1.412953e+07,1.676878e+08
typeconstructiontypeid,76.0,5.973684e+00,2.294157e-01,4.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00
storytypeid,47.0,7.000000e+00,0.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00
propertylandusetypeid,52441.0,2.610000e+02,0.000000e+00,2.610000e+02,2.610000e+02,2.610000e+02,2.610000e+02,2.610000e+02
heatingorsystemtypeid,33935.0,3.966288e+00,2.562506e+00,1.000000e+00,2.000000e+00,2.000000e+00,7.000000e+00,2.400000e+01
architecturalstyletypeid,70.0,7.100000e+00,2.665670e+00,2.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00,2.100000e+01
airconditioningtypeid,13638.0,2.438041e+00,3.846176e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.300000e+01
id,52441.0,1.497270e+06,8.594393e+05,3.490000e+02,7.579550e+05,1.500810e+06,2.241534e+06,2.982270e+06
basementsqft,47.0,6.789787e+02,7.118252e+02,3.800000e+01,2.635000e+02,5.120000e+02,8.095000e+02,3.560000e+03
bathroomcnt,52441.0,2.299403e+00,1.022772e+00,0.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,1.800000e+01
bedroomcnt,52441.0,3.300681e+00,9.490939e-01,0.000000e+00,3.000000e+00,3.000000e+00,4.000000e+00,1.400000e+01
buildingqualitytypeid,33740.0,6.264167e+00,1.716162e+00,1.000000e+00,5.000000e+00,6.000000e+00,8.000000e+00,1.200000e+01
calculatedbathnbr,52304.0,2.304738e+00,1.017966e+00,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,1.800000e+01
decktypeid,389.0,6.600000e+01,0.000000e+00,6.600000e+01,6.600000e+01,6.600000e+01,6.600000e+01,6.600000e+01
finishedfloor1squarefeet,4381.0,1.545611e+03,6.748653e+02,1.840000e+02,1.151000e+03,1.410000e+03,1.759000e+03,6.912000e+03
calculatedfinishedsquarefeet,52359.0,1.922891e+03,1.004366e+03,1.280000e+02,1.268000e+03,1.659000e+03,2.306000e+03,2.192900e+04
finishedsquarefeet12,52194.0,1.925046e+03,1.004275e+03,1.280000e+02,1.270000e+03,1.660500e+03,2.308000e+03,2.192900e+04
finishedsquarefeet50,4381.0,1.566375e+03,7.445229e+02,1.840000e+02,1.152000e+03,1.414000e+03,1.770000e+03,1.246700e+04
finishedsquarefeet6,165.0,1.241079e+03,7.769591e+02,3.800000e+02,7.840000e+02,1.008000e+03,1.320000e+03,5.598000e+03
fips,52441.0,6.049132e+03,2.102907e+01,6.037000e+03,6.037000e+03,6.037000e+03,6.059000e+03,6.111000e+03
fireplacecnt,7243.0,1.209858e+00,5.128851e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,5.000000e+00
fullbathcnt,52304.0,2.239580e+00,9.932070e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,1.800000e+01
garagecarcnt,18015.0,1.948987e+00,5.499437e-01,0.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,1.400000e+01
garagetotalsqft,18015.0,4.958757e+02,1.570447e+02,0.000000e+00,4.260000e+02,4.620000e+02,5.670000e+02,4.251000e+03
hashottuborspa,1515.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
latitude,52441.0,3.402254e+07,2.739787e+05,3.334062e+07,3.382691e+07,3.402378e+07,3.418715e+07,3.481877e+07
longitude,52441.0,-1.181942e+08,3.566626e+05,-1.194754e+08,-1.184007e+08,-1.181531e+08,-1.179292e+08,-1.175546e+08
lotsizesquarefeet,52072.0,1.133962e+04,8.674763e+04,2.360000e+02,5.583000e+03,6.840500e+03,8.798250e+03,6.971010e+06
poolcnt,11096.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
poolsizesum,867.0,5.183183e+02,1.564682e+02,2.400000e+01,4.245000e+02,5.000000e+02,6.000000e+02,1.500000e+03
pooltypeid10,444.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
pooltypeid2,1071.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
pooltypeid7,10009.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
rawcensustractandblock,52441.0,6.049443e+07,2.086892e+05,6.037101e+07,6.037401e+07,6.037620e+07,6.059042e+07,6.111009e+07
regionidcity,51404.0,3.350144e+04,4.917519e+04,3.491000e+03,1.244700e+04,2.481200e+04,4.022700e+04,3.965560e+05
regionidcounty,52441.0,2.524588e+03,8.039900e+02,1.286000e+03,1.286000e+03,3.101000e+03,3.101000e+03,3.101000e+03
regionidneighborhood,19033.0,1.802671e+05,1.598249e+05,6.952000e+03,4.113100e+04,1.182080e+05,2.745140e+05,7.641670e+05
regionidzip,52415.0,9.663585e+04,4.605108e+03,9.598200e+04,9.620600e+04,9.641200e+04,9.699500e+04,3.996750e+05
roomcnt,52441.0,1.893709e+00,3.146437e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00,1.500000e+01
threequarterbathnbr,6724.0,1.013682e+00,1.426160e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,7.000000e+00
unitcnt,33847.0,1.000916e+00,3.121163e-02,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,3.000000e+00
yardbuildingsqft17,1937.0,3.376278e+02,2.500216e+02,1.100000e+01,2.000000e+02,2.800000e+02,4.000000e+02,3.191000e+03
yardbuildingsqft26,63.0,2.256190e+02,1.885051e+02,1.200000e+01,7.150000e+01,1.800000e+02,3.170000e+02,8.680000e+02
yearbuilt,52325.0,1.963394e+03,2.313357e+01,1.878000e+03,1.950000e+03,1.961000e+03,1.979000e+03,2.016000e+03
numberofstories,14561.0,1.413914e+00,5.406765e-01,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,6.000000e+00
fireplaceflag,81.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
structuretaxvaluedollarcnt,52357.0,1.965338e+05,2.543401e+05,1.290000e+02,7.707100e+04,1.318110e+05,2.263340e+05,9.164901e+06
taxvaluedollarcnt,52440.0,5.296882e+05,7.518946e+05,1.000000e+03,1.937475e+05,3.736120e+05,6.193012e+05,4.906124e+07
assessmentyear,52441.0,2.016000e+03,0.000000e+00,2.016000e+03,2.016000e+03,2.016000e+03,2.016000e+03,2.016000e+03
landtaxvaluedollarcnt,52440.0,3.334655e+05,5.705278e+05,1.610000e+02,7.602075e+04,2.180320e+05,4.086068e+05,4.895220e+07
taxamount,52437.0,6.453511e+03,8.755568e+03,4.918000e+01,2.656220e+03,4.647740e+03,7.377500e+03,5.866393e+05
taxdelinquencyyear,2079.0,1.410245e+01,2.394972e+00,4.000000e+00,1.400000e+01,1.500000e+01,1.500000e+01,9.900000e+01
censustractandblock,52318.0,6.050240e+13,1.859036e+12,6.037101e+13,6.037401e+13,6.037620e+13,6.059042e+13,4.830301e+14
id,52441.0,3.885989e+04,2.234801e+04,0.000000e+00,1.954600e+04,3.892700e+04,5.809200e+04,7.761200e+04
logerror,52441.0,1.829849e-02,1.775010e-01,-4.655420e+00,-2.463880e-02,7.010779e-03,4.069204e-02,5.262999e+00

In [6]:
def nulls_by_rows(df):
    return pd.concat([
        df.isna().sum(axis=1).rename('n_missing'),
        df.isna().mean(axis=1).rename('percent_missing'),
    ], axis=1).value_counts().sort_index()

In [7]:
def nulls_by_columns(df):
    return pd.concat([
        df.isna().sum().rename('count'),
        df.isna().mean().rename('percent')
    ], axis=1)

In [8]:
listof = nulls_by_columns(df)
listof

                        count   percent
parcelid                    0  0.000000
typeconstructiontypeid  52365  0.998551
storytypeid             52394  0.999104
propertylandusetypeid       0  0.000000
heatingorsystemtypeid   18506  0.352892
...                       ...       ...
buildingclassdesc       52441  1.000000
heatingorsystemdesc     18506  0.352892
propertylandusedesc         0  0.000000
storydesc               52394  0.999104
typeconstructiondesc    52365  0.998551

[69 rows x 2 columns]

In [9]:
def handle_missing_values(df, prop_required_column, prop_required_row):
    n_required_column = round(df.shape[0] * prop_required_column)
    n_required_row = round(df.shape[1] * prop_required_row)
    df = df.dropna(axis=0, thresh=n_required_row)
    df = df.dropna(axis=1, thresh=n_required_column)
    return df

In [10]:
def overview(df):
    print('--- Shape: {}'.format(df.shape))
    print('--- Info')
    df.info()
    print('--- Column Descriptions')
    print(df.describe(include='all'))

In [11]:
overview = overview(df)
overview

--- Shape: (52441, 69)
--- Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52441 entries, 0 to 52440
Data columns (total 69 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   parcelid                      52441 non-null  int64
 1   typeconstructiontypeid        76 non-null     float64
 2   storytypeid                   47 non-null     float64
 3   propertylandusetypeid         52441 non-null  float64
 4   heatingorsystemtypeid         33935 non-null  float64
 5   buildingclasstypeid           0 non-null      object
 6   architecturalstyletypeid      70 non-null     float64
 7   airconditioningtypeid         13638 non-null  float64
 8   id                            52441 non-null  int64
 9   basementsqft                  47 non-null     float64
 10  bathroomcnt                   52441 non-null  float64
 11  bedroomcnt                    52441 non-null  float64
 12  buildingqualitytypeid         33740 non-null  float64
 13  calculatedbathnbr             52304 non-null  float64
 14  decktypeid                    389 non-null    float64
 15  finishedfloor1squarefeet      4381 non-null   float64
 16  calculatedfinishedsquarefeet  52359 non-null  float64
 17  finishedsquarefeet12          52194 non-null  float64
 18  finishedsquarefeet13          0 non-null      object
 19  finishedsquarefeet15          0 non-null      object
 20  finishedsquarefeet50          4381 non-null   float64
 21  finishedsquarefeet6           165 non-null    float64
 22  fips                          52441 non-null  float64
 23  fireplacecnt                  7243 non-null   float64
 24  fullbathcnt                   52304 non-null  float64
 25  garagecarcnt                  18015 non-null  float64
 26  garagetotalsqft               18015 non-null  float64
 27  hashottuborspa                1515 non-null   float64
 28  latitude                      52441 non-null  float64
 29  longitude                     52441 non-null  float64
 30  lotsizesquarefeet             52072 non-null  float64
 31  poolcnt                       11096 non-null  float64
 32  poolsizesum                   867 non-null    float64
 33  pooltypeid10                  444 non-null    float64
 34  pooltypeid2                   1071 non-null   float64
 35  pooltypeid7                   10009 non-null  float64
 36  propertycountylandusecode     52441 non-null  object
 37  propertyzoningdesc            33848 non-null  object
 38  rawcensustractandblock        52441 non-null  float64
 39  regionidcity                  51404 non-null  float64
 40  regionidcounty                52441 non-null  float64
 41  regionidneighborhood          19033 non-null  float64
 42  regionidzip                   52415 non-null  float64
 43  roomcnt                       52441 non-null  float64
 44  threequarterbathnbr           6724 non-null   float64
 45  unitcnt                       33847 non-null  float64
 46  yardbuildingsqft17            1937 non-null   float64
 47  yardbuildingsqft26            63 non-null     float64
 48  yearbuilt                     52325 non-null  float64
 49  numberofstories               14561 non-null  float64
 50  fireplaceflag                 81 non-null     float64
 51  structuretaxvaluedollarcnt    52357 non-null  float64
 52  taxvaluedollarcnt             52440 non-null  float64
 53  assessmentyear                52441 non-null  float64
 54  landtaxvaluedollarcnt         52440 non-null  float64
 55  taxamount                     52437 non-null  float64
 56  taxdelinquencyflag            2079 non-null   object
 57  taxdelinquencyyear            2079 non-null   float64
 58  censustractandblock           52318 non-null  float64
 59  id                            52441 non-null  int64
 60  logerror                      52441 non-null  float64
 61  transactiondate               52441 non-null  object
 62  airconditioningdesc           13638 non-null  object
 63  architecturalstyledesc        70 non-null     object
 64  buildingclassdesc             0 non-null      object
 65  heatingorsystemdesc           33935 non-null  object
 66  propertylandusedesc           52441 non-null  object
 67  storydesc                     47 non-null     object
 68  typeconstructiondesc          76 non-null     object
dtypes: float64(52), int64(3), object(14)
memory usage: 27.6+ MB
--- Column Descriptions
            parcelid  typeconstructiontypeid  storytypeid  \
count   5.244100e+04               76.000000         47.0
unique           NaN                     NaN          NaN
top              NaN                     NaN          NaN
freq             NaN                     NaN          NaN
mean    1.299912e+07                5.973684          7.0
std     3.411444e+06                0.229416          0.0
min     1.071186e+07                4.000000          7.0
25%     1.151022e+07                6.000000          7.0
50%     1.257764e+07                6.000000          7.0
75%     1.412953e+07                6.000000          7.0
max     1.676878e+08                6.000000          7.0

        propertylandusetypeid  heatingorsystemtypeid buildingclasstypeid  \
count                 52441.0           33935.000000                   0
unique                    NaN                    NaN                   0
top                       NaN                    NaN                 NaN
freq                      NaN                    NaN                 NaN
mean                    261.0               3.966288                 NaN
std                       0.0               2.562506                 NaN
min                     261.0               1.000000                 NaN
25%                     261.0               2.000000                 NaN
50%                     261.0               2.000000                 NaN
75%                     261.0               7.000000                 NaN
max                     261.0              24.000000                 NaN

        architecturalstyletypeid  airconditioningtypeid            id  \
count                   70.00000           13638.000000  5.244100e+04
unique                       NaN                    NaN           NaN
top                          NaN                    NaN           NaN
freq                         NaN                    NaN           NaN
mean                     7.10000               2.438041  1.497270e+06
std                      2.66567               3.846176  8.594393e+05
min                      2.00000               1.000000  3.490000e+02
25%                      7.00000               1.000000  7.579550e+05
50%                      7.00000               1.000000  1.500810e+06
75%                      7.00000               1.000000  2.241534e+06
max                     21.00000              13.000000  2.982270e+06

        basementsqft  ...            id      logerror  transactiondate  \
count      47.000000  ...  52441.000000  52441.000000            52441
unique           NaN  ...           NaN           NaN              257
top              NaN  ...           NaN           NaN       2017-06-30
freq             NaN  ...           NaN           NaN              810
mean      678.978723  ...  38859.892946      0.018298              NaN
std       711.825226  ...  22348.009638      0.177501              NaN
min        38.000000  ...      0.000000     -4.655420              NaN
25%       263.500000  ...  19546.000000     -0.024639              NaN
50%       512.000000  ...  38927.000000      0.007011              NaN
75%       809.500000  ...  58092.000000      0.040692              NaN
max      3560.000000  ...  77612.000000      5.262999              NaN

        airconditioningdesc  architecturalstyledesc  buildingclassdesc  \
count                 13638                      70                  0
unique                    4                       5                  0
top                 Central            Contemporary                NaN
freq                  11895                      62                NaN
mean                    NaN                     NaN                NaN
std                     NaN                     NaN                NaN
min                     NaN                     NaN                NaN
25%                     NaN                     NaN                NaN
50%                     NaN                     NaN                NaN
75%                     NaN                     NaN                NaN
max                     NaN                     NaN                NaN

        heatingorsystemdesc        propertylandusedesc storydesc  \
count                 33935                      52441        47
unique                    9                          1         1
top                 Central  Single Family Residential  Basement
freq                  20736                      52441        47
mean                    NaN                        NaN       NaN
std                     NaN                        NaN       NaN
min                     NaN                        NaN       NaN
25%                     NaN                        NaN       NaN
50%                     NaN                        NaN       NaN
75%                     NaN                        NaN       NaN
max                     NaN                        NaN       NaN

       typeconstructiondesc
count                    76
unique                    2
top                   Frame
freq                     75
mean                    NaN
std                     NaN
min                     NaN
25%                     NaN
50%                     NaN
75%                     NaN
max                     NaN

[11 rows x 69 columns]

## Prepare

1. Remove any properties that are likely to be something other than single unit properties. (e.g. no duplexes, no land/lot, ...). There are multiple ways to estimate that a property is a single unit, and there is not a single "right" answer.

2. Create a function that will drop rows or columns based on the percent of values that are missing: handle_missing_values(df, prop_required_column, prop_required_row).
- The input:
  -  A dataframe
  -  A number between 0 and 1 that represents the proportion, for each column, of rows with non-missing values required to keep the column. i.e. if prop_required_column = .6, then you are requiring a column to have at least 60% of values not-NA (no more than 40% missing).
  -  A number between 0 and 1 that represents the proportion, for each row, of columns/variables with non-missing values required to keep the row. For example, if prop_required_row = .75, then you are requiring a row to have at least 75% of variables with a non-missing value (no more that 25% missing).
- The output:
  -  The dataframe with the columns and rows dropped as indicated. Be sure to drop the columns prior to the rows in your function.
- hint:
  -  Look up the dropna documentation.
  -  You will want to compute a threshold from your input values (prop_required) and total number of rows or columns.

3. Encapsulate your work inside of functions in a wrangle_zillow.py module.

In [12]:
def handle_missing_values(df, prop_required_column, prop_required_row):
    n_required_column = round(df.shape[0] * prop_required_column)
    n_required_row = round(df.shape[1] * prop_required_row)
    df = df.dropna(axis=0, thresh=n_required_row)
    df = df.dropna(axis=1, thresh=n_required_column)
    return df

In [23]:
missing_values = handle_missing_values(df,.5,.25)
missing_values

,parcelid,propertylandusetypeid,heatingorsystemtypeid,id,bathroomcnt,bedroomcnt,buildingqualitytypeid,calculatedbathnbr,calculatedfinishedsquarefeet,finishedsquarefeet12,...,taxvaluedollarcnt,assessmentyear,landtaxvaluedollarcnt,taxamount,censustractandblock,id,logerror,transactiondate,heatingorsystemdesc,propertylandusedesc
0,14297519,261.0,NaN,1727539,3.5,4.0,NaN,3.5,3100.0,3100.0,...,1023282.0,2016.0,537569.0,11013.72,6.059063e+13,0,0.025595,2017-01-01,None,Single Family Residential
1,17052889,261.0,NaN,1387261,1.0,2.0,NaN,1.0,1465.0,1465.0,...,464000.0,2016.0,376000.0,5672.48,6.111001e+13,1,0.055619,2017-01-01,None,Single Family Residential
2,14186244,261.0,NaN,11677,2.0,3.0,NaN,2.0,1243.0,1243.0,...,564778.0,2016.0,479489.0,6488.30,6.059022e+13,2,0.005383,2017-01-01,None,Single Family Residential
3,12177905,261.0,2.0,2288172,3.0,4.0,8.0,3.0,2376.0,2376.0,...,145143.0,2016.0,36225.0,1777.51,6.037300e+13,3,-0.103410,2017-01-01,Central,Single Family Residential
4,12095076,261.0,2.0,781532,3.0,4.0,9.0,3.0,2962.0,2962.0,...,773303.0,2016.0,496619.0,9516.26,6.037461e+13,6,-0.001011,2017-01-01,Central,Single Family Residential
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52436,12412492,261.0,2.0,2274245,2.0,4.0,6.0,2.0,1633.0,1633.0,...,346534.0,2016.0,221068.0,4175.08,6.037555e+13,77607,0.001082,2017-09-19,Central,Single Family Residential
52437,11000655,261.0,2.0,673515,2.0,2.0,6.0,2.0,1286.0,1286.0,...,354621.0,2016.0,283704.0,4478.43,6.037101e+13,77609,0.020615,2017-09-20,Central,Single Family Residential
52438,17239384,261.0,NaN,2968375,2.0,4.0,NaN,2.0,1612.0,1612.0,...,67205.0,2016.0,16522.0,1107.48,6.111008e+13,77610,0.013209,2017-09-21,None,Single Family Residential
52439,12773139,261.0,2.0,1843709,1.0,3.0,4.0,1.0,1032.0,1032.0,...,49546.0,2016.0,16749.0,876.43,6.037434e+13,77611,0.037129,2017-09-21,Central,Single Family Residential
52440,12826780,261.0,2.0,1187175,2.0,3.0,6.0,2.0,1762.0,1762.0,...,522000.0,2016.0,382000.0,6317.15,6.037503e+13,77612,0.007204,2017-09-25,Central,Single Family Residential