In [1]:
import pandas as pd
import seaborn as sns
import acquire

## Acquire and Summarize

1. Acquire data from the cloud database.

    You will want to end with a single dataframe. Include the logerror field and all other fields related to the properties that are available. You will end up using all the tables in the database.

    <b><i>Be sure to do the correct join (inner, outer, etc.). We do not want to eliminate properties purely because they may have a null value for airconditioningtypeid.</i></b> - Only include properties with a transaction in 2017, and include only the last transaction for each property (so no duplicate property ID's), along with zestimate error and date of transaction. (Hint: read the docs for the .duplicated method) - Only include properties that have a latitude and longitude value.
    
    
2. Summarize your data (summary stats, info, dtypes, shape, distributions, value_counts, etc.)


3. Write a function that takes in a dataframe of observations and attributes and returns a dataframe where each row is an atttribute name, the first column is the number of rows with missing values for that attribute, and the second column is percent of total rows that have missing values for that attribute. Run the function and document takeaways from this on how you want to handle missing values.

In [2]:
df = acquire.zillow_data()
df

,parcelid,typeconstructiontypeid,storytypeid,propertylandusetypeid,heatingorsystemtypeid,buildingclasstypeid,architecturalstyletypeid,airconditioningtypeid,id,basementsqft,...,id,logerror,transactiondate,airconditioningdesc,architecturalstyledesc,buildingclassdesc,heatingorsystemdesc,propertylandusedesc,storydesc,typeconstructiondesc
0,17173851,NaN,NaN,261.0,NaN,NaN,NaN,NaN,787,NaN,...,389.0,0.088469,2017-01-03,None,None,None,None,Single Family Residential,None,None
1,10821119,NaN,NaN,261.0,2.0,NaN,NaN,NaN,1702,NaN,...,402.0,0.025629,2017-01-03,None,None,None,Central,Single Family Residential,None,None
2,11007640,NaN,NaN,261.0,2.0,NaN,NaN,1.0,2412,NaN,...,2699.0,0.020360,2017-01-12,Central,None,None,Central,Single Family Residential,None,None
3,11457850,NaN,NaN,261.0,7.0,NaN,NaN,NaN,3770,NaN,...,2229.0,0.054233,2017-01-11,None,None,None,Floor/Wall,Single Family Residential,None,None
4,12591550,NaN,NaN,261.0,2.0,NaN,NaN,NaN,8197,NaN,...,3038.0,-0.016170,2017-01-13,None,None,None,Central,Single Family Residential,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2152981,13915341,NaN,NaN,261.0,NaN,NaN,NaN,NaN,2982148,NaN,...,NaN,NaN,None,None,None,None,None,Single Family Residential,None,None
2152982,14360869,NaN,NaN,261.0,NaN,NaN,NaN,NaN,2982193,NaN,...,71174.0,0.086432,2017-08-29,None,None,None,None,Single Family Residential,None,None
2152983,13952473,NaN,NaN,261.0,NaN,NaN,NaN,NaN,2982226,NaN,...,NaN,NaN,None,None,None,None,None,Single Family Residential,None,None
2152984,14367624,NaN,NaN,261.0,NaN,NaN,NaN,NaN,2982275,NaN,...,NaN,NaN,None,None,None,None,None,Single Family Residential,None,None
2152985,12385768,NaN,NaN,261.0,2.0,NaN,NaN,1.0,2982282,NaN,...,NaN,NaN,None,Central,None,None,Central,Single Family Residential,None,None

In [3]:
df.shape

(2152986, 69)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2152986 entries, 0 to 2152985
Data columns (total 69 columns):
 #   Column                        Dtype
---  ------                        -----
 0   parcelid                      int64
 1   typeconstructiontypeid        float64
 2   storytypeid                   float64
 3   propertylandusetypeid         float64
 4   heatingorsystemtypeid         float64
 5   buildingclasstypeid           float64
 6   architecturalstyletypeid      float64
 7   airconditioningtypeid         float64
 8   id                            int64
 9   basementsqft                  float64
 10  bathroomcnt                   float64
 11  bedroomcnt                    float64
 12  buildingqualitytypeid         float64
 13  calculatedbathnbr             float64
 14  decktypeid                    float64
 15  finishedfloor1squarefeet      float64
 16  calculatedfinishedsquarefeet  float64
 17  finishedsquarefeet12          float64
 18  finishedsquarefeet13          float64
 19  finishedsquarefeet15          float64
 20  finishedsquarefeet50          float64
 21  finishedsquarefeet6           float64
 22  fips                          float64
 23  fireplacecnt                  float64
 24  fullbathcnt                   float64
 25  garagecarcnt                  float64
 26  garagetotalsqft               float64
 27  hashottuborspa                float64
 28  latitude                      float64
 29  longitude                     float64
 30  lotsizesquarefeet             float64
 31  poolcnt                       float64
 32  poolsizesum                   float64
 33  pooltypeid10                  float64
 34  pooltypeid2                   float64
 35  pooltypeid7                   float64
 36  propertycountylandusecode     object
 37  propertyzoningdesc            object
 38  rawcensustractandblock        float64
 39  regionidcity                  float64
 40  regionidcounty                float64
 41  regionidneighborhood          float64
 42  regionidzip                   float64
 43  roomcnt                       float64
 44  threequarterbathnbr           float64
 45  unitcnt                       float64
 46  yardbuildingsqft17            float64
 47  yardbuildingsqft26            float64
 48  yearbuilt                     float64
 49  numberofstories               float64
 50  fireplaceflag                 float64
 51  structuretaxvaluedollarcnt    float64
 52  taxvaluedollarcnt             float64
 53  assessmentyear                float64
 54  landtaxvaluedollarcnt         float64
 55  taxamount                     float64
 56  taxdelinquencyflag            object
 57  taxdelinquencyyear            float64
 58  censustractandblock           float64
 59  id                            float64
 60  logerror                      float64
 61  transactiondate               object
 62  airconditioningdesc           object
 63  architecturalstyledesc        object
 64  buildingclassdesc             object
 65  heatingorsystemdesc           object
 66  propertylandusedesc           object
 67  storydesc                     object
 68  typeconstructiondesc          object
dtypes: float64(56), int64(2), object(11)
memory usage: 1.1+ GB

In [5]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
parcelid,2152986.0,1.309662e+07,5.172433e+06,1.071172e+07,1.165907e+07,1.259850e+07,1.405608e+07,1.696019e+08
typeconstructiontypeid,2658.0,5.981189e+00,3.486948e-01,4.000000e+00,6.000000e+00,6.000000e+00,6.000000e+00,1.300000e+01
storytypeid,1535.0,7.000000e+00,0.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00
propertylandusetypeid,2152986.0,2.610000e+02,1.226738e-02,2.610000e+02,2.610000e+02,2.610000e+02,2.610000e+02,2.790000e+02
heatingorsystemtypeid,1424939.0,4.107412e+00,2.560808e+00,1.000000e+00,2.000000e+00,2.000000e+00,7.000000e+00,2.400000e+01
buildingclasstypeid,1.0,4.000000e+00,NaN,4.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00,4.000000e+00
architecturalstyletypeid,2393.0,7.187631e+00,2.739586e+00,2.000000e+00,7.000000e+00,7.000000e+00,7.000000e+00,2.100000e+01
airconditioningtypeid,513912.0,2.405684e+00,3.785911e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.300000e+01
id,2152986.0,1.490843e+06,8.608785e+05,1.000000e+00,7.451292e+05,1.490640e+06,2.235865e+06,2.982282e+06
basementsqft,1538.0,6.511905e+02,5.520788e+02,2.000000e+01,2.617500e+02,5.195000e+02,8.895000e+02,8.516000e+03
bathroomcnt,2152975.0,2.230676e+00,9.992799e-01,0.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,3.200000e+01
bedroomcnt,2152975.0,3.287193e+00,9.547934e-01,0.000000e+00,3.000000e+00,3.000000e+00,4.000000e+00,2.500000e+01
buildingqualitytypeid,1420314.0,6.146929e+00,1.697330e+00,1.000000e+00,4.000000e+00,6.000000e+00,8.000000e+00,1.200000e+01
calculatedbathnbr,2139310.0,2.244216e+00,9.869366e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,3.200000e+01
decktypeid,12571.0,6.600000e+01,0.000000e+00,6.600000e+01,6.600000e+01,6.600000e+01,6.600000e+01,6.600000e+01
finishedfloor1squarefeet,163587.0,1.497903e+03,6.327567e+02,1.000000e+00,1.130000e+03,1.373000e+03,1.697000e+03,3.130300e+04
calculatedfinishedsquarefeet,2144500.0,1.862852e+03,1.222120e+03,1.000000e+00,1.257000e+03,1.623000e+03,2.208000e+03,9.525760e+05
finishedsquarefeet12,2136589.0,1.864441e+03,9.694559e+02,1.000000e+00,1.260000e+03,1.624000e+03,2.210000e+03,6.369200e+04
finishedsquarefeet13,4.0,8.775000e+02,4.196042e+02,5.500000e+02,6.415000e+02,7.360000e+02,9.720000e+02,1.488000e+03
finishedsquarefeet15,12.0,3.605583e+03,4.635044e+03,4.410000e+02,1.046000e+03,2.502000e+03,3.223000e+03,1.721400e+04
finishedsquarefeet50,163587.0,1.512740e+03,6.892231e+02,3.000000e+00,1.134000e+03,1.375000e+03,1.704000e+03,4.190600e+04
finishedsquarefeet6,7898.0,1.430515e+03,1.229188e+04,1.170000e+02,8.000000e+02,9.810000e+02,1.336000e+03,9.525760e+05
fips,2152986.0,6.048377e+03,2.043332e+01,6.037000e+03,6.037000e+03,6.037000e+03,6.059000e+03,6.111000e+03
fireplacecnt,287606.0,1.178731e+00,4.743761e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,9.000000e+00
fullbathcnt,2139310.0,2.189198e+00,9.666120e-01,1.000000e+00,2.000000e+00,2.000000e+00,3.000000e+00,3.200000e+01
garagecarcnt,698664.0,1.926653e+00,5.696367e-01,0.000000e+00,2.000000e+00,2.000000e+00,2.000000e+00,2.500000e+01
garagetotalsqft,698664.0,4.886608e+02,1.605000e+02,0.000000e+00,4.200000e+02,4.600000e+02,5.370000e+02,7.749000e+03
hashottuborspa,49333.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
latitude,2152986.0,3.400747e+07,2.481646e+05,3.333991e+07,3.383213e+07,3.400455e+07,3.417047e+07,3.481965e+07
longitude,2152986.0,-1.181912e+08,3.439653e+05,-1.194758e+08,-1.183845e+08,-1.181447e+08,-1.179442e+08,-1.175543e+08
lotsizesquarefeet,2139545.0,1.107215e+04,2.656321e+05,1.000000e+02,5.633000e+03,6.760000e+03,8.551000e+03,3.710005e+08
poolcnt,413252.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
poolsizesum,27860.0,5.200931e+02,1.913151e+02,1.900000e+01,4.310000e+02,4.960000e+02,5.950000e+02,1.741000e+04
pooltypeid10,16429.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
pooltypeid2,32904.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
pooltypeid7,379857.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
rawcensustractandblock,2152986.0,6.048687e+07,2.028071e+05,6.037101e+07,6.037402e+07,6.037571e+07,6.059042e+07,6.111009e+07
regionidcity,2112344.0,3.506683e+04,5.226415e+04,3.491000e+03,1.244700e+04,2.483200e+04,4.483300e+04,3.965560e+05
regionidcounty,2152986.0,2.552861e+03,7.951585e+02,1.286000e+03,1.286000e+03,3.101000e+03,3.101000e+03,3.101000e+03
regionidneighborhood,779148.0,1.863760e+05,1.614874e+05,6.952000e+03,4.146600e+04,1.188250e+05,2.746950e+05,7.641670e+05
regionidzip,2149599.0,9.658921e+04,4.276406e+03,9.598200e+04,9.619200e+04,9.638700e+04,9.698700e+04,3.996750e+05
roomcnt,2152969.0,1.864968e+00,3.122039e+00,0.000000e+00,0.000000e+00,0.000000e+00,5.000000e+00,9.600000e+01
threequarterbathnbr,232192.0,1.013812e+00,1.383251e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,7.000000e+00
unitcnt,1424918.0,1.001423e+00,1.319584e-01,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.020000e+02
yardbuildingsqft17,71454.0,3.414551e+02,2.378094e+02,1.000000e+01,2.000000e+02,2.880000e+02,4.050000e+02,7.983000e+03
yardbuildingsqft26,2484.0,2.724932e+02,3.380360e+02,1.000000e+01,1.000000e+02,1.680000e+02,3.150000e+02,4.144000e+03
yearbuilt,2143646.0,1.960949e+03,2.216238e+01,1.801000e+03,1.949000e+03,1.958000e+03,1.976000e+03,2.016000e+03
numberofstories,590868.0,1.386003e+00,5.377729e-01,1.000000e+00,1.000000e+00,1.000000e+00,2.000000e+00,4.100000e+01
fireplaceflag,2849.0,1.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00
structuretaxvaluedollarcnt,2146049.0,1.787187e+05,2.717851e+05,1.000000e+00,7.414000e+04,1.224390e+05,2.038630e+05,6.640493e+07
taxvaluedollarcnt,2152493.0,4.618965e+05,6.996804e+05,1.000000e+00,1.881630e+05,3.276710e+05,5.345210e+05,9.842891e+07
assessmentyear,2152985.0,2.015999e+03,5.561274e-02,2.000000e+03,2.016000e+03,2.016000e+03,2.016000e+03,2.016000e+03
landtaxvaluedollarcnt,2152484.0,2.837140e+05,5.026689e+05,1.000000e+00,7.966700e+04,1.838940e+05,3.452790e+05,8.892195e+07
taxamount,2148544.0,5.634879e+03,8.179021e+03,1.850000e+00,2.534918e+03,4.108900e+03,6.414300e+03,1.337756e+06
taxdelinquencyyear,41260.0,1.388403e+01,2.431295e+00,0.000000e+00,1.400000e+01,1.400000e+01,1.500000e+01,9.900000e+01
censustractandblock,2140663.0,6.048664e+13,3.599283e+11,-1.000000e+00,6.037402e+13,6.037571e+13,6.059042e+13,4.830301e+14
id,52442.0,3.886063e+04,2.234844e+04,0.000000e+00,1.954625e+04,3.892750e+04,5.809350e+04,7.761300e+04
logerror,52442.0,1.829437e-02,1.775018e-01,-4.655420e+00,-2.463935e-02,7.009984e-03,4.069098e-02,5.262999e+00

In [6]:
def nulls_by_rows(df):
    return pd.concat([
        df.isna().sum(axis=1).rename('n_missing'),
        df.isna().mean(axis=1).rename('percent_missing'),
    ], axis=1).value_counts().sort_index()

In [7]:
def nulls_by_columns(df):
    return pd.concat([
        df.isna().sum().rename('count'),
        df.isna().mean().rename('percent')
    ], axis=1)

In [8]:
listof = nulls_by_columns(df)
listof

                          count   percent
parcelid                      0  0.000000
typeconstructiontypeid  2150328  0.998765
storytypeid             2151451  0.999287
propertylandusetypeid         0  0.000000
heatingorsystemtypeid    728047  0.338157
...                         ...       ...
buildingclassdesc       2152985  1.000000
heatingorsystemdesc      728047  0.338157
propertylandusedesc           0  0.000000
storydesc               2151451  0.999287
typeconstructiondesc    2150328  0.998765

[69 rows x 2 columns]

In [9]:
def handle_missing_values(df, prop_required_column, prop_required_row):
    n_required_column = round(df.shape[0] * prop_required_column)
    n_required_row = round(df.shape[1] * prop_required_row)
    df = df.dropna(axis=0, thresh=n_required_row)
    df = df.dropna(axis=1, thresh=n_required_column)
    return df

In [10]:
def overview(df):
    print('--- Shape: {}'.format(df.shape))
    print('--- Info')
    df.info()
    print('--- Column Descriptions')
    print(df.describe(include='all'))

In [11]:
overview = overview(df)
overview

--- Shape: (2152986, 69)
--- Info
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2152986 entries, 0 to 2152985
Data columns (total 69 columns):
 #   Column                        Dtype
---  ------                        -----
 0   parcelid                      int64
 1   typeconstructiontypeid        float64
 2   storytypeid                   float64
 3   propertylandusetypeid         float64
 4   heatingorsystemtypeid         float64
 5   buildingclasstypeid           float64
 6   architecturalstyletypeid      float64
 7   airconditioningtypeid         float64
 8   id                            int64
 9   basementsqft                  float64
 10  bathroomcnt                   float64
 11  bedroomcnt                    float64
 12  buildingqualitytypeid         float64
 13  calculatedbathnbr             float64
 14  decktypeid                    float64
 15  finishedfloor1squarefeet      float64
 16  calculatedfinishedsquarefeet  float64
 17  finishedsquarefeet12          float64
 18  finishedsquarefeet13          float64
 19  finishedsquarefeet15          float64
 20  finishedsquarefeet50          float64
 21  finishedsquarefeet6           float64
 22  fips                          float64
 23  fireplacecnt                  float64
 24  fullbathcnt                   float64
 25  garagecarcnt                  float64
 26  garagetotalsqft               float64
 27  hashottuborspa                float64
 28  latitude                      float64
 29  longitude                     float64
 30  lotsizesquarefeet             float64
 31  poolcnt                       float64
 32  poolsizesum                   float64
 33  pooltypeid10                  float64
 34  pooltypeid2                   float64
 35  pooltypeid7                   float64
 36  propertycountylandusecode     object
 37  propertyzoningdesc            object
 38  rawcensustractandblock        float64
 39  regionidcity                  float64
 40  regionidcounty                float64
 41  regionidneighborhood          float64
 42  regionidzip                   float64
 43  roomcnt                       float64
 44  threequarterbathnbr           float64
 45  unitcnt                       float64
 46  yardbuildingsqft17            float64
 47  yardbuildingsqft26            float64
 48  yearbuilt                     float64
 49  numberofstories               float64
 50  fireplaceflag                 float64
 51  structuretaxvaluedollarcnt    float64
 52  taxvaluedollarcnt             float64
 53  assessmentyear                float64
 54  landtaxvaluedollarcnt         float64
 55  taxamount                     float64
 56  taxdelinquencyflag            object
 57  taxdelinquencyyear            float64
 58  censustractandblock           float64
 59  id                            float64
 60  logerror                      float64
 61  transactiondate               object
 62  airconditioningdesc           object
 63  architecturalstyledesc        object
 64  buildingclassdesc             object
 65  heatingorsystemdesc           object
 66  propertylandusedesc           object
 67  storydesc                     object
 68  typeconstructiondesc          object
dtypes: float64(56), int64(2), object(11)
memory usage: 1.1+ GB
--- Column Descriptions
            parcelid  typeconstructiontypeid  storytypeid  \
count   2.152986e+06             2658.000000       1535.0
unique           NaN                     NaN          NaN
top              NaN                     NaN          NaN
freq             NaN                     NaN          NaN
mean    1.309662e+07                5.981189          7.0
std     5.172433e+06                0.348695          0.0
min     1.071172e+07                4.000000          7.0
25%     1.165907e+07                6.000000          7.0
50%     1.259850e+07                6.000000          7.0
75%     1.405608e+07                6.000000          7.0
max     1.696019e+08               13.000000          7.0

        propertylandusetypeid  heatingorsystemtypeid  buildingclasstypeid  \
count            2.152986e+06           1.424939e+06                  1.0
unique                    NaN                    NaN                  NaN
top                       NaN                    NaN                  NaN
freq                      NaN                    NaN                  NaN
mean             2.610000e+02           4.107412e+00                  4.0
std              1.226738e-02           2.560808e+00                  NaN
min              2.610000e+02           1.000000e+00                  4.0
25%              2.610000e+02           2.000000e+00                  4.0
50%              2.610000e+02           2.000000e+00                  4.0
75%              2.610000e+02           7.000000e+00                  4.0
max              2.790000e+02           2.400000e+01                  4.0

        architecturalstyletypeid  airconditioningtypeid            id  \
count                2393.000000          513912.000000  2.152986e+06
unique                       NaN                    NaN           NaN
top                          NaN                    NaN           NaN
freq                         NaN                    NaN           NaN
mean                    7.187631               2.405684  1.490843e+06
std                     2.739586               3.785911  8.608785e+05
min                     2.000000               1.000000  1.000000e+00
25%                     7.000000               1.000000  7.451292e+05
50%                     7.000000               1.000000  1.490640e+06
75%                     7.000000               1.000000  2.235865e+06
max                    21.000000              13.000000  2.982282e+06

        basementsqft  ...            id      logerror  transactiondate  \
count    1538.000000  ...  52442.000000  52442.000000            52442
unique           NaN  ...           NaN           NaN              258
top              NaN  ...           NaN           NaN       2017-06-30
freq             NaN  ...           NaN           NaN              810
mean      651.190507  ...  38860.631917      0.018294              NaN
std       552.078809  ...  22348.437271      0.177502              NaN
min        20.000000  ...      0.000000     -4.655420              NaN
25%       261.750000  ...  19546.250000     -0.024639              NaN
50%       519.500000  ...  38927.500000      0.007010              NaN
75%       889.500000  ...  58093.500000      0.040691              NaN
max      8516.000000  ...  77613.000000      5.262999              NaN

        airconditioningdesc  architecturalstyledesc  \
count                513912                    2393
unique                    7                       7
top                 Central            Contemporary
freq                 447959                    2124
mean                    NaN                     NaN
std                     NaN                     NaN
min                     NaN                     NaN
25%                     NaN                     NaN
50%                     NaN                     NaN
75%                     NaN                     NaN
max                     NaN                     NaN

                                     buildingclassdesc  heatingorsystemdesc  \
count                                                1              1424939
unique                                               1                   11
top     Buildings having wood or wood and steel frames              Central
freq                                                 1               828497
mean                                               NaN                  NaN
std                                                NaN                  NaN
min                                                NaN                  NaN
25%                                                NaN                  NaN
50%                                                NaN                  NaN
75%                                                NaN                  NaN
max                                                NaN                  NaN

              propertylandusedesc  storydesc  typeconstructiondesc
count                     2152986       1535                  2658
unique                          2          1                     4
top     Single Family Residential   Basement                 Frame
freq                      2152985       1535                  2616
mean                          NaN        NaN                   NaN
std                           NaN        NaN                   NaN
min                           NaN        NaN                   NaN
25%                           NaN        NaN                   NaN
50%                           NaN        NaN                   NaN
75%                           NaN        NaN                   NaN
max                           NaN        NaN                   NaN

[11 rows x 69 columns]

## Prepare

1. Remove any properties that are likely to be something other than single unit properties. (e.g. no duplexes, no land/lot, ...). There are multiple ways to estimate that a property is a single unit, and there is not a single "right" answer.

2. Create a function that will drop rows or columns based on the percent of values that are missing: handle_missing_values(df, prop_required_column, prop_required_row).
- The input:
  -  A dataframe
  -  A number between 0 and 1 that represents the proportion, for each column, of rows with non-missing values required to keep the column. i.e. if prop_required_column = .6, then you are requiring a column to have at least 60% of values not-NA (no more than 40% missing).
  -  A number between 0 and 1 that represents the proportion, for each row, of columns/variables with non-missing values required to keep the row. For example, if prop_required_row = .75, then you are requiring a row to have at least 75% of variables with a non-missing value (no more that 25% missing).
- The output:
  -  The dataframe with the columns and rows dropped as indicated. Be sure to drop the columns prior to the rows in your function.
- hint:
  -  Look up the dropna documentation.
  -  You will want to compute a threshold from your input values (prop_required) and total number of rows or columns.

3. Encapsulate your work inside of functions in a wrangle_zillow.py module.

In [13]:
def handle_missing_values(df, prop_required_column, prop_required_row):
    n_required_column = round(df.shape[0] * prop_required_column)
    n_required_row = round(df.shape[1] * prop_required_row)
    df = df.dropna(axis=0, thresh=n_required_row)
    df = df.dropna(axis=1, thresh=n_required_column)
    return df

In [14]:
missing_values = handle_missing_values(df)
missing_values

TypeError: handle_missing_values() missing 2 required positional arguments: 'prop_required_column' and 'prop_required_row'